In [5]:
import numpy as np
import pandas as pd

In [24]:
# Step 1: Create a NumPy array with random numbers
np.random.seed(42)
random_array = np.random.randint(1,101, size=[100,2]) # could have duplicates

In [25]:
# Step 2: Convert the NumPy array to a Pandas DataFrame
df = pd.DataFrame(random_array, columns=['Column1', 'Column2'])
df.head()

   Column1  Column2
0       52       93
1       15       72
2       61       21
3       83       87
4       75       75

Using pd.qcut()

.qcut() tries to create bins such that each bin has approximately same number of data points. Buf if there are duplicates, bin edges might not be unique

In [26]:
df['column1_bins']=pd.qcut(df['Column1'],q=10,duplicates='drop')
freq_by_default_bin = df['column1_bins'].value_counts().sort_index()
df_default_bins=pd.DataFrame({'custom_bins':freq_by_default_bin.index,'frequency':freq_by_default_bin.values})
df_default_bins['bin_number'] = range(len(df_default_bins))
df_default_bins

    custom_bins  frequency  bin_number
0  (0.999, 4.9]         10           0
1   (4.9, 14.8]         10           1
2  (14.8, 28.0]         12           2
3  (28.0, 35.0]          9           3
4  (35.0, 52.0]         10           4
5  (52.0, 60.4]          9           5
6  (60.4, 65.4]         10           6
7  (65.4, 80.2]         10           7
8  (80.2, 89.0]         11           8
9  (89.0, 99.0]          9           9

Using pd.cut()

In [27]:
custom_bins=[0,10,20,30,40,50,60,70,80,90,100]
df['custom_bins'] = pd.cut(df['Column2'],bins=custom_bins)
freq_by_bin = df['custom_bins'].value_counts().sort_index()
df_custom_bins=pd.DataFrame({'custom_bins':freq_by_bin.index,'frequency':freq_by_bin.values})
df_custom_bins['bin_number'] = range(len(df_custom_bins))
df_custom_bins

  custom_bins  frequency  bin_number
0     (0, 10]         11           0
1    (10, 20]          7           1
2    (20, 30]         10           2
3    (30, 40]          7           3
4    (40, 50]         13           4
5    (50, 60]          9           5
6    (60, 70]         10           6
7    (70, 80]         12           7
8    (80, 90]         10           8
9   (90, 100]         11           9